### PR TITLE
fixed #4

### LINKED ISSUE #4: raise RuntimeError('Attempted to use a closed Session.') RuntimeError: Attempted to use a closed Session.
Hey guys, 

Thanks for putting this together  - it's rare to find ML & ROS tutorials. This is exactly what I needed :+1: 
I am trying to run the usb_cam example: `roslaunch tensorflow_object_detector usb_cam_detector.launch` and it looks like the program runs fine until this line: `(boxes, scores, classes, num_detections) = sess.run([boxes, scores, classes, num_detections], feed_dict={image_tensor: image_np_expanded})`

The error below is what I get. It loops over in image_cb and prints the following error every time it gets to the line mentioned above:

```
[ERROR] [1539275044.021065]: bad callback: <bound method detector.image_cb of <__main__.detector instance at 0x7fc7073b5488>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/gal/Tensorflow_ws/src/tensorflow_object_detector/scripts/detect_ros.py", line 121, in image_cb
    feed_dict={image_tensor: image_np_expanded})
  File "/home/gal/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/gal/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1033, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.
```

### PR DESCRIPTION
**Pull request by vinay0410**
This pull fixes #4. I have also faced this issue earlier and was caused due to opening a closed ```tf session``` variable.
Therefore, I have made it a class variable and initialized it in the constructor, preventing it being from destructed before the object is destructed.

And, it works.

### CODE REVIEW

**Comment by vinay0410** [comment]
Hi @codebot , I have made the changes as mentioned.

Also, I would like to mention that the folder ```src/object_detection``` contains lots of redundant files relating to model builders and anchor generators which aren't required at all.

They are necessary for training and evaluation, but not for inference (detection).

As, you can see only 2 modules are being imported from that folder [here](https://github.com/osrf/tensorflow_object_detector/blob/f303c5ad883875853ae27ba76ba9bc36fd524587/scripts/detect_ros.py#L27-L28), only for the purpose of drawing bounding boxes and labelling.

I was thinking of removing that redundancy in another pull, since that's not a bug, just a refinement of codebase.

Would that be fine ?

**Comment by vinay0410** [comment]
Yes, a new package for training could be developed, and this one could be left for detection only.
A training package would have other intricacies, and obviously other use cases, therefore I believe they must be separate.

Yes, that would be of interest.
This is already a detection package, so I will just submit a pull to remove redundant files.

Thanks!

**Comment by vinay0410** [comment]
sure, that will be great !
I am thinking of refining detection first, and then consequently adding writing scripts for training.
Since, training is much more complex and would require some additions configurations.

Would that be fine ?

**Comment by vinay0410** [comment]
Fine, I will surely do that.
Thanks!

**Comment by GalMoore** [comment]
Training scripts would be insanely useful. Looking forward !

**Pull request merged**
